# Generated by Django 5.0 on 2023-12-12 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunidades_criadas', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(related_name='comunidades_membro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('data_denuncia', models.DateTimeField(auto_now_add=True)),
                ('autor_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publicacao_denunciada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artes.publicacao')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonimo', models.CharField(max_length=50)),
                ('nome_social', models.CharField(blank=True, max_length=50, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
