# Generated by Django 4.2.5 on 2023-12-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artes', '0004_followers_usuarioperfil_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfil',
            name='icone',
            field=models.ImageField(default='midia/user_icon.png', upload_to='midia'),
        ),
    ]
