# Generated by Django 5.0 on 2023-12-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artes', '0005_alter_usuarioperfil_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfil',
            name='icone',
            field=models.ImageField(default='midia\\midia\x07bstract-user-flat-3.png', upload_to='midia'),
        ),
    ]
