# Generated by Django 5.0 on 2023-12-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artes', '0008_alter_usuarioperfil_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfil',
            name='icone',
            field=models.ImageField(default='', upload_to='midia'),
        ),
    ]
