# Generated by Django 5.0 on 2023-12-15 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artes', '0009_alter_usuarioperfil_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artes.usuarioperfil'),
        ),
    ]
