# Generated by Django 5.0 on 2023-12-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artes', '0010_alter_publicacao_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfil',
            name='icone',
            field=models.ImageField(blank=True, default='', null=True, upload_to='midia'),
        ),
    ]
